# Generated by Django 4.2.7 on 2025-11-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('reviewer', 'Reviewer'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='reader', max_length=50, verbose_name='role'),
        ),
    ]
