# Generated by Django 4.2.7 on 2025-11-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSeedTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_key', models.CharField(max_length=100, unique=True)),
                ('seeded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
