# Generated by Django 4.2.7 on 2025-11-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_dataseedtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link_buy',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
