# Generated by Django 4.2.7 on 2025-11-27 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('copyright', 'Copyright Violation'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=50, verbose_name='reason')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('moderator_note', models.TextField(blank=True, verbose_name='moderator note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModeratorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'Hide Content'), ('delete', 'Delete Content'), ('warn', 'Warn User'), ('suspend', 'Suspend User'), ('ban', 'Ban User'), ('approve', 'Approve Content'), ('reject', 'Reject Report')], max_length=50, verbose_name='action')),
                ('object_id', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='moderation.report')),
            ],
            options={
                'verbose_name': 'moderator action',
                'verbose_name_plural': 'moderator actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', '-created_at'], name='moderation__reporte_350be5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='moderation__content_408935_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatoraction',
            index=models.Index(fields=['moderator', '-created_at'], name='moderation__moderat_28caf0_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatoraction',
            index=models.Index(fields=['action', '-created_at'], name='moderation__action_52fbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatoraction',
            index=models.Index(fields=['content_type', 'object_id'], name='moderation__content_6ba1bc_idx'),
        ),
    ]
