# Generated by Django 4.2.7 on 2025-11-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/covers/', verbose_name='cover image')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20, verbose_name='visibility')),
                ('book_count', models.PositiveIntegerField(default=0, verbose_name='book count')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('follow', 'New Follower'), ('review_like', 'Review Liked'), ('review_comment', 'Review Commented'), ('review_mention', 'Mentioned in Review'), ('comment_reply', 'Comment Replied'), ('comment_like', 'Comment Liked'), ('new_review', 'New Review from Following'), ('collection_item', 'Added to Collection')], max_length=50, verbose_name='type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='social_noti_user_id_d8b56a_idx'), models.Index(fields=['notification_type', '-created_at'], name='social_noti_notific_d62ee9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'follow',
                'verbose_name_plural': 'follows',
                'indexes': [models.Index(fields=['follower', '-created_at'], name='social_foll_followe_31933d_idx'), models.Index(fields=['content_type', 'object_id', '-created_at'], name='social_foll_content_99f27f_idx')],
                'unique_together': {('follower', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='books.book')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='social.collection')),
            ],
            options={
                'verbose_name': 'collection item',
                'verbose_name_plural': 'collection items',
                'ordering': ['order', '-added_at'],
                'indexes': [models.Index(fields=['collection', '-added_at'], name='social_coll_collect_74c802_idx'), models.Index(fields=['book', '-added_at'], name='social_coll_book_id_4d0b3e_idx')],
                'unique_together': {('collection', 'book')},
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'is_active'], name='social_coll_user_id_20d143_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['visibility', '-created_at'], name='social_coll_visibil_119119_idx'),
        ),
    ]
