# Generated by Django 4.2.7 on 2025-11-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('review_like', 'Review Liked'), ('review_comment', 'Review Commented'), ('review_mention', 'Mentioned in Review'), ('comment_reply', 'Comment Replied'), ('comment_like', 'Comment Liked'), ('new_review', 'New Review from Following'), ('collection_item', 'Added to Collection'), ('rank_upgrade', 'Rank Upgraded'), ('system', 'System Message')], max_length=50, verbose_name='type'),
        ),
    ]
