# Generated by Django 4.2.7 on 2025-11-02 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('system_type', models.CharField(blank=True, choices=[('WTR', 'Want to Read'), ('READING', 'Reading'), ('READ', 'Read')], max_length=20, null=True, verbose_name='system type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20, verbose_name='visibility')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='shelves/covers/', verbose_name='cover image')),
                ('book_count', models.PositiveIntegerField(default=0, verbose_name='book count')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shelf',
                'verbose_name_plural': 'shelves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='page')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='percent')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reading progress',
                'verbose_name_plural': 'reading progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_items', to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shelves.shelf')),
            ],
            options={
                'verbose_name': 'shelf item',
                'verbose_name_plural': 'shelf items',
                'ordering': ['order', '-added_at'],
                'indexes': [models.Index(fields=['shelf', '-added_at'], name='shelves_she_shelf_i_a23fb3_idx'), models.Index(fields=['book', '-added_at'], name='shelves_she_book_id_1fd882_idx')],
                'unique_together': {('shelf', 'book')},
            },
        ),
        migrations.AddIndex(
            model_name='shelf',
            index=models.Index(fields=['user', 'is_active'], name='shelves_she_user_id_467714_idx'),
        ),
        migrations.AddIndex(
            model_name='shelf',
            index=models.Index(fields=['system_type'], name='shelves_she_system__6df257_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('user', 'system_type')},
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['user', '-updated_at'], name='shelves_rea_user_id_327f27_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['book', '-updated_at'], name='shelves_rea_book_id_4a1720_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'book')},
        ),
    ]
